apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumleap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumleap
  template:
    metadata:
      labels:
        app: quantumleap
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: quantumleap
          image: orchestracities/quantumleap:latest
          ports:
            - containerPort: 8668
          env:
            - name: CRATE_HOST
              value: cratedb
            - name: REDIS_HOST
              value: redis
            - name: QL_DEFAULT_DB
              value: crate