apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik
data:
  dynamic.yaml: |
    tcp:
      routers:
        mqtt-tls:
          entryPoints:
            - mqtt-tls
          rule: "HostSNI(`*`)"
          service: rabbitmq
          tls:
            passthrough: true
      services:
        rabbitmq:
          loadBalancer:
            servers:
              - address: "rabbitmq:8883"